from datetime import datetime, timezone


def generate_report(stats: dict, changes: dict) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# Hardware Data Update Report",
        f"",
        f"**Generated:** {now}",
        f"",
    ]

    if stats:
        lines.append("## Validation Summary")
        lines.append("")
        lines.append("| Category | Total | Valid | Errors |")
        lines.append("|----------|-------|-------|--------|")
        for cat, cat_stats in stats.items():
            total = cat_stats.get("total", 0)
            errors = cat_stats.get("errors", 0)
            valid = "Yes" if errors == 0 else "No"
            lines.append(f"| {cat} | {total} | {valid} | {errors} |")
        lines.append("")

    if changes:
        lines.append("## Changes")
        lines.append("")

        has_any = False

        added = changes.get("added", {})
        if any(len(v) > 0 for v in added.values()):
            has_any = True
            lines.append("### New Components")
            lines.append("")
            for cat, items in added.items():
                if items:
                    lines.append(f"**{cat}** ({len(items)} new):")
                    for item in items[:20]:
                        name = item.get("name", "Unknown")
                        msrp = item.get("msrp", 0)
                        lines.append(f"- {name} (${msrp:.2f})")
                    if len(items) > 20:
                        lines.append(f"- ... and {len(items) - 20} more")
                    lines.append("")

        removed = changes.get("removed", {})
        if any(len(v) > 0 for v in removed.values()):
            has_any = True
            lines.append("### Removed Components")
            lines.append("")
            for cat, slugs in removed.items():
                if slugs:
                    lines.append(f"**{cat}** ({len(slugs)} removed):")
                    for slug in slugs[:20]:
                        lines.append(f"- `{slug}`")
                    if len(slugs) > 20:
                        lines.append(f"- ... and {len(slugs) - 20} more")
                    lines.append("")

        updated = changes.get("updated", {})
        if any(len(v) > 0 for v in updated.values()):
            has_any = True
            lines.append("### Updated Components")
            lines.append("")
            for cat, items in updated.items():
                if items:
                    lines.append(f"**{cat}** ({len(items)} updated):")
                    for slug, fields in items[:20]:
                        lines.append(f"- `{slug}`: {', '.join(fields)}")
                    if len(items) > 20:
                        lines.append(f"- ... and {len(items) - 20} more")
                    lines.append("")

        if not has_any:
            lines.append("No changes detected.")
            lines.append("")

    lines.append("---")
    lines.append("*Auto-generated by PCForge data pipeline*")
    return "\n".join(lines)
